env:
  # กำหนดเป้าหมาย (Target)
  parameters:
    target: "http://34.2.27.127:8888/" 
    
  # กำหนด Context 
  contexts:
    - name: "Default Context"
      # รวม/ไม่รวม URL ในการสแกน
      urls:
        - "http://34.2.27.127:8888/"

jobs:
  # 1. Job: แอดออน (เพื่อให้แน่ใจว่า add-on ที่จำเป็นถูกติดตั้ง)
  - type: addonInstall
    parameters:
      ids: 
        - pscanrules
        - pscanrulesBeta
        - ascanrules
        - ascanrulesBeta

  # 2. Job: สำรวจเว็บไซต์ด้วย Traditional Spider
  - type: spider
    parameters:
      context: "Default Context"
      url: "http://34.2.27.127:8888/"
      maxDuration: 5 # นาที

  # 3. Job: สำรวจเว็บไซต์ด้วย AJAX Spider (สำหรับแอปพลิเคชันสมัยใหม่)
  - type: ajaxSpider
    parameters:
      context: "Default Context"
      url: "http://34.2.27.127:8888/"
      maxDuration: 5 # นาที

  # 4. Job: รอให้ Passive Scan ทำงานเสร็จ
  - type: passiveScan-wait
    parameters:
      maxDuration: 5 # นาที

  # 5. Job: Active Scan (โจมตีเป้าหมายเพื่อหาช่องโหว่)
  - type: activeScan
    parameters:
      context: "Default Context"
      policy: "Default Policy"
      maxDuration: 60 # นาที

  # 6. Job: สร้างรายงาน
  - type: report
    parameters:
      template: traditional-html
      reportFileName: "ZAP_Report_Target.html"
      reportDir: "reports" # โฟลเดอร์ที่จะเก็บรายงาน