# zap_plan.yaml
env:
  # กำหนด Target URL ในส่วน env (แนะนำ)
  target: ${target}
  
  # กำหนดชื่อเซสชัน
  name: ZAP CI/CD Scan

contexts:
  # กำหนด Contexts (จำเป็นถ้าต้องการ Authentication หรือ Scope ที่ซับซ้อน)
  - name: Default Context
    # ตั้งค่ารวมถึง URL ที่ ZAP จะทำการสแกนเท่านั้น
    urls:
      - ${target}
    
jobs:
  # 1. Job Spidering (สำรวจเส้นทาง)
  - type: spider
    name: spider-target
    parameters:
      maxDuration: 5
      maxDepth: 5
    # ตั้งค่า Context ที่ใช้
    context: Default Context
    
  # 2. Job Active Scan (โจมตีหาช่องโหว่)
  - type: activeScan
    name: active-scan
    parameters:
      policy: Default Policy
    context: Default Context
    
  # 3. Job Report (ต้องมี)
  - type: generateReport
    name: generate-report
    parameters:
      template: traditional-html
      reportDir: /zap/wrk/
      reportFile: zap_report.html