# zap_plan.yaml - ZAP Automation Plan ตัวอย่าง
---
# ส่วนที่ 1: env (สภาพแวดล้อม) - กำหนดตัวแปรและตั้งค่าหลัก
env:
  name: My Zap CI/CD Scan
  # ตัวแปรที่ใช้ซ้ำได้ตลอดทั้ง Plan
  parameters:
    target: "https://google.com" # URL เป้าหมายของการสแกน
    zap_url: "http://localhost:8081"
    #api_key: "SOME_SECRET_API_KEY_OR_EMPTY" # ควรใช้ API Key ใน production

# ส่วนที่ 2: jobs (งาน) - ลำดับของขั้นตอนที่ ZAP จะดำเนินการ
jobs:

  # 1. Job: กำหนด Context (ขอบเขตการสแกน)
  - name: define-context
    type: context
    parameters:
      contextFile: "" # ใช้ไฟล์ Context ภายนอก (ถ้ามี)
      context:
        name: Default Context
        # กำหนดขอบเขต: อนุญาตเฉพาะ URL เป้าหมายเท่านั้น
        includePaths:
          - "{{ target }}.*"
        excludePaths: []

  # 2. Job: Spider Scan (ค้นหาลิงก์และทรัพยากร)
  - name: spider-target
    type: spider
    parameters:
      context: Default Context
      url: "{{ target }}"
      maxDuration: 5 # จำกัดเวลาการคลานเป็น 5 นาที (เพื่อป้องกัน Timeouts ใน CI)
      maxDepth: 5    # คลานลึกสุด 5 ระดับ
    tests:
      # Job นี้จะ Fail หาก Spider ไม่พบ URL ที่จะสแกน
      - name: Min URLs found
        type: stats
        stat: stats.spider.urls_found
        operator: '>='
        value: 5 # ต้องพบ URL อย่างน้อย 5 URL

  # 3. Job: Active Scan (สแกนหาช่องโหว่)
  - name: active-scan
    type: activeScan
    parameters:
      context: Default Context
      policy: Default Policy # ใช้ Policy การสแกนเริ่มต้นของ ZAP
      maxRuleDuration: 5 # จำกัดเวลาต่อ Rule เป็น 5 นาที
      maxScanDuration: 60 # จำกัดเวลาการสแกนทั้งหมดเป็น 60 นาที (1 ชั่วโมง)
    tests:
      # กำหนดเงื่อนไขการล้มเหลวของ Pipeline
      - name: High Risk Alerts
        type: alert
        alertSet:
          # หากพบช่องโหว่ระดับ High หรือ Medium ให้ Job นี้ล้มเหลว
          - policyId: 0 # ทุก Policy ID
            severity: High
            fail: true # หากพบ ให้ล้มเหลว
            quantity: 0 # พบจำนวน 0 หมายถึง ห้ามพบเลย
          - policyId: 0
            severity: Medium
            fail: true
            quantity: 0

  # 4. Job: Report (สร้างรายงานผลลัพธ์)
  - name: generate-report
    type: report
    parameters:
      template: traditional-html # ใช้ Template รายงาน HTML แบบดั้งเดิม
      title: ZAP Security Scan Report - {{ target }}
      description: Automatic scan generated by CI/CD pipeline.
      reportDir: /zap/wrk/ # ไดเรกทอรีสำหรับบันทึกรายงาน (Map จาก Host)
      reportFile: zap_report.html