env:
    
  # กำหนด Context 
  contexts:
    - name: "Default Context"
      # รวม/ไม่รวม URL ในการสแกน
      urls:
        - "http://34.2.27.127:8888/"

jobs:
  # 2. Job: สำรวจเว็บไซต์ด้วย Traditional Spider
  - type: spider
    parameters:
      context: "Default Context"
      url: "http://34.2.27.127:8888/"
      maxDuration: 5 # นาที

  # 3. Job: สำรวจเว็บไซต์ด้วย AJAX Spider (สำหรับแอปพลิเคชันสมัยใหม่)
  - type: spiderAjax
    parameters:
      context: "Default Context"
      url: "http://34.2.27.127:8888/"
      maxDuration: 5 # นาที

  # 4. Job: รอให้ Passive Scan ทำงานเสร็จ
  - type: passiveScan-wait
    parameters:
      maxDuration: 5 # นาที

  # 5. Job: Active Scan (โจมตีเป้าหมายเพื่อหาช่องโหว่)
  - type: activeScan
    parameters:
      context: "Default Context"
      policy: "Default Policy"

  # 6. Job: สร้างรายงาน
  - type: report
    parameters:
      template: traditional-html
      reportFile: "ZAP_Report_Target.html"
      reportDir: "reports" # โฟลเดอร์ที่จะเก็บรายงาน